UserParameter=mariadb.mysqladmin.ping,/usr/local/bin/galera-check.sh mysql.ping
UserParameter=mariadb.galera.value[*],/usr/local/bin/galera-check.sh galera.value "$1"
UserParameter=mariadb.galera.primary,/usr/local/bin/galera-check.sh galera.primary
UserParameter=mariadb.galera.ready,/usr/local/bin/galera-check.sh galera.ready
UserParameter=mariadb.galera.connected,/usr/local/bin/galera-check.sh galera.connected
UserParameter=mariadb.galera.synced,/usr/local/bin/galera-check.sh galera.synced
UserParameter=haproxy.backends_up_count,/usr/local/bin/galera-check.sh haproxy.backends_up_count
UserParameter=service.process.running[*],/usr/local/bin/galera-check.sh process.running "$1"
UserParameter=keepalived.vip.present[*],/usr/local/bin/galera-check.sh keepalived.vip.present "$1"
UserParameter=haproxy.mysql_front.listen,MYSQL_FRONT_PORT=3307 /usr/local/bin/galera-check.sh haproxy.mysql_front.listen
